name: Auto Login and Email Result

on:
  schedule:
    - cron: "0 0 */60 * *"
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install playwright
          playwright install
          playwright install-deps

      - name: Use GitHub secret
        run: 
          echo ${{ secrets.USERNAME1 }}
          echo ${{ secrets.PASSWORD1 }}
          echo ${{ secrets.PANEL_INDEX1 }}
        
      - name: Run login script
        env:
          USERNAME1: ${{ secrets.USERNAME1 }}
          PASSWORD1: ${{ secrets.PASSWORD1 }}
          PANEL_INDEX1: ${{ secrets.PANEL_INDEX1 }}
        run: python script.py
